name: kontrollu_saglik
description: none

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  carousel_slider: ^2.2.1
  cupertino_icons: ^1.0.0
  dio: ^4.0.6

  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.1.1
  font_awesome_flutter: ^8.8.1
  getwidget: ^2.0.5
  glass: ^1.0.1+1
  google_fonts: ^2.3.2
  lottie: ^1.2.2
  onboarding: ^3.1.0
  responsive_sizer: ^3.0.5+1
  rive: ^0.8.4
  scrollable_positioned_list: ^0.1.7
  shimmer_animation: ^2.1.0
  sizer: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^5.5.2
  video_player: ^2.2.19
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
